version: '3'
services:
  redis:
    image: redis
    ports:
      - "32774:6379" # Map container port 6379 to host port 32774
    networks:
      - mynetwork
    environment:
      - REDIS_DATA_PROTECTION_KEY=YourDataProtectionKeyHere

  mongodb:
    image: mongo
    ports:
      - "27017:27017" # Map container port 27017 to host port 27017
    networks:
      - mynetwork
    environment:
      - MONGO_INITDB_DATABASE=DevLog

networks:
  mynetwork:
