name: Deploy to Google Cloud Run

on:
 push:
    branches:
      - main

jobs:
 deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Google Container Registry
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/gardenhub-repo/gardenhub-img:latest

    - name: Deploy to Google Cloud Run
      uses: google-github-actions/deploy-cloudrun@v0.3.0
      with:
        service: your-service-name
        image: gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/gardenhub-repo/gardenhub-img:latest
        credentials: ${{ secrets.GCR_JSON_KEY }}
        region: us-central1
        allowUnauthenticated: true
